import { Inter, Raleway } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

const raleway = Raleway({
    subsets: ["latin"],
    display: "swap",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <script defer src="https://cdn.tailwindcss.com"></script>
            </head>
            <body className={raleway.className}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
